spring.application.name=yedocb

# 서버 포트
server.port=8080

## MyBatis
mybatis.mapper-locations=classpath*:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

## PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/yedocb
spring.datasource.username=postgres
spring.datasource.password=postgres
